spring:
  datasource:
    url: jdbc:mysql://47.94.157.36:3306/live_team?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lin1997426520.
  redis:
    host:  47.94.157.36 #个人服务器
    password: 123456
    port: 6379
    timeout: 3000
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  supportMethodsArguments: true
  reasonable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.live.liveteam.entityin
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 47.94.157.36:22122
url:
  fastdfsurl: http://47.94.157.36:8888